server:
  port: 8080

logging:
  level:
    root: debug
    org.hibernate: debug
    org.org.springframework.web: debug
#
#springdoc:
#  model-and-view-allowed: true
---
spring:
  main:
    allow-bean-definition-overriding: true

  rabbitmq:
    #    for locally
    host: localhost
#        for docker
#    host: payments-rabbit
    port: 5672
    username: guest
    password: guest

  liquibase:
    enabled: true
    change-log: db/changelog/changelog.yaml
    clear-checksums: true

  datasource:
    username: root
    password: root
#    for docker
#    url: jdbc:mysql://payments-mysql:3306/payments?createDatabaseIfNotExist=true
#    for locally
    url: jdbc:mysql://localhost:3306/payments?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  messages:
    basename: lang/messages
    always-use-message-format: false
    encoding: UTF-8
    fallback-to-system-locale: true

#RabbitMQ alert queue configuration
alert-queue:
  name: "payment-queue"
  routing-key: "mail-notification"
  exchange: "payment-exchange"

springdoc:
  model-and-view-allowed: true

---
spring:
  config:
    activate:
      on-profile: test-env

  liquibase:
    clear-checksums: true
    change-log: classpath:db/changelog/changelog.yaml

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    database: h2
    hibernate:
      ddl-auto: none

  datasource:
    driver-class-name: org.h2.Driver
    username: h2db
    password: h2db
    url: jdbc:h2:mem:payments_db_test;MODE=MySQL;NON_KEYWORDS=USER;



