server:
  port: 9090

spring:

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

alert-queue:
  name:
    sender-queue: "sender-payment-queue"
    receiver-queue: "receiver-payment-queue"
