server:
  port: 8080
---
spring:

  liquibase:
    enabled: true
    change-log: db/changelog/changelog.yaml
    clear-checksums: true

  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/payments?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    database: mysql
---
spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:h2:mem:db_test;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: h2db
    password: h2db

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    clear-checksums: true

logging:
  level:
    org:
      hibernate:
        sql: info



