server:
  port: 9090

spring:

  rabbitmq:
#    for locally
#    host: localhost
#    for docker
    host: payments-rabbit
    port: 5672
    username: guest
    password: guest

  mail:
    host: "smtp.gmail.com"
    port: 587
    username: "payments.service.feedback@gmail.com"
    password: "rixucdtzwfiphxsy"
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true

#RabbitMQ alert queue configuration
alert-queue:
  name: "payment-queue"
  routing-key: "mail-notification"
  exchange: "payment-exchange"

