server:
  port: 9090

spring:

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  mail:
    host: "smtp.gmail.com"
    port: 587
    username: "payments.service.feedback@gmail.com"
    password: "rixucdtzwfiphxsy"
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true

alert-queue:
  name: "payment-queue"

