server:
  port: 8181

logging:
  level:
    root: info
    org.hibernate: info
    org.org.springframework.web: info

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: payments_monitoring_db

springdoc:
  model-and-view-allowed: true
  swagger-ui:
    disable-swagger-default-url: true
    path: /payments-monitoring-swagger